version: "3.8"
services:
  db:
    image: postgres:15
    container_name: chessdb_postgres
    environment:
      POSTGRES_USER: adamAziz
      POSTGRES_PASSWORD: PACIFICPUNCH1998!
      POSTGRES_DB: chessdb
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data